### ISSUE TITLE
Installer Mono Error

### ISSUE THREAD

**Issue by Zerenis** [ModTheGungeon/ETGMod.Installer#3]
Whenever I load up terminal and type mono and then put a space and bring in the installer program I get an error.

Entering the holy realm of ETGMod.
Asset 0: ETGMod.Installer.Assets.background.png
Asset 1: ETGMod.Installer.Assets.icons.main.png
Asset 2: ETGMod.Installer.Assets.icons.main-large.png
Asset 3: ETGMod.Installer.Assets.icons.open.png
Asset 4: ETGMod.Installer.Assets.icons.uninstall.png
System.UnauthorizedAccessException: Access to the path "/Library/Application Support/ETGMod" is denied.

Followed by many lines of code. It attempts to open the installer program but only lasts for a fraction of a second before closing itself and doing nothing else. I am able to use older versions of the installer successfully, but once I try to install everything it prompts me to get the most recent installer.

Is there a folder I need to create? Or any kind of acceptions I might need to add? Any assistance that can be provided would be greatly appreciated. Thank you.

**Comment by zatherz** [comment]
Fixed https://github.com/ModTheGungeon/ETGMod.Installer/commit/3cc2841517a31c01d91584956e6141e5b76440c7

**Comment by kozie** [comment]
Doesn't seems to be fixed. I downloaded 17.01.30 pre-release and confirmed that the above commit has been merged into that version. The error, however, is still present. Running mono with sudo works tho but one does not simply want to do that ;)

**Comment by zatherz** [comment]
That makes no sense... the issue is fixed in that commit. Are you sure you weren't running an older installer version by accident? Is the error message exactly the same thing?

**Comment by kozie** [comment]
I downloaded the latest version twice to be sure.. but let me just try another time. I will include the log also. will post back later ;)

**Comment by Zerenis** [comment]
I attempted the install with the updated file and got what I believe is the same error. The same issues happened. I open terminal, enter mono then a space and then drag in the file. I am then given the following:
Entering the holy realm of ETGMod.
Asset 0: ETGMod.Installer.Assets.background.png
Asset 1: ETGMod.Installer.Assets.icons.main.png
Asset 2: ETGMod.Installer.Assets.icons.main-large.png
Asset 3: ETGMod.Installer.Assets.icons.open.png
Asset 4: ETGMod.Installer.Assets.icons.uninstall.png
System.UnauthorizedAccessException: Access to the path "/Library/Application Support/ETGMod" is denied.
  at System.IO.Directory.CreateDirectoriesInternal (System.String path) [0x00070] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.IO.Directory.CreateDirectory (System.String path) [0x000a4] in <8f2c484307284b51944a1a13a14c0266>:0 
  at ETGModInstaller.ETGInstallerSettings.get_ConfigurationPath () [0x000be] in <b4eeb55e4d4c4c0ea5914b7bd1cbf973>:0 
  at ETGModInstaller.ETGInstallerSettings.Load () [0x0000f] in <b4eeb55e4d4c4c0ea5914b7bd1cbf973>:0 
  at ETGModInstaller.InstallerWindow.onHandleCreated (System.Object sender, System.EventArgs e) [0x0001d] in <b4eeb55e4d4c4c0ea5914b7bd1cbf973>:0 
  at (wrapper delegate-invoke) <Module>:invoke_void_object_EventArgs (object,System.EventArgs)
  at System.Windows.Forms.Control.OnHandleCreated (System.EventArgs e) [0x0001c] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
  at System.Windows.Forms.Form.OnHandleCreated (System.EventArgs e) [0x00016] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
  at System.Windows.Forms.Control.WmCreate (System.Windows.Forms.Message& m) [0x00000] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
  at System.Windows.Forms.Control.WndProc (System.Windows.Forms.Message& m) [0x001d7] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
  at System.Windows.Forms.ScrollableControl.WndProc (System.Windows.Forms.Message& m) [0x00000] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
  at System.Windows.Forms.ContainerControl.WndProc (System.Windows.Forms.Message& m) [0x0003c] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
  at System.Windows.Forms.Form.WndProc (System.Windows.Forms.Message& m) [0x0015c] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
  at System.Windows.Forms.Control+ControlWindowTarget.OnMessage (System.Windows.Forms.Message& m) [0x00000] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
  at System.Windows.Forms.Control+ControlNativeWindow.WndProc (System.Windows.Forms.Message& m) [0x0000b] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
  at System.Windows.Forms.NativeWindow.WndProc (System.IntPtr hWnd, System.Windows.Forms.Msg msg, System.IntPtr wParam, System.IntPtr lParam) [0x0008e] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0

The installer attempts to open but only lasts for a brief moment before closing. I have tried it after creating a folder in Macintosh/Library/ApplicationSupport named ETGMod and without that folder and have received the same result each time.

**Comment by kozie** [comment]
I haven't been testing yet, tho i can say i most probably had the same error @Zerenis had.

Please check if the home variable has been set correctly. It seems empty seeing the log results.

**Comment by zatherz** [comment]
Try the latest prerelease (17.02.07).

**Comment by kozie** [comment]
Works like a charm! Thanks @zatherz!
